<?php
namespace Primecontent\Tests\Controllers;

/**
*  Corresponding Class to test YourClass class
*
*  For each class in your library, there should be a corresponding Unit-Test for it
*  Unit-Tests should be as much as possible independent from other test going on.
*
*  @author Álex Martin|Juan Manuel Castillo
*/

use Primecontent\Tests\BaseAPITestCase;

class CompoundFieldControllerTest extends BaseAPITestCase {

    /**
     * @testdox Listing items
     */
    public function testListItemsSuccess(){
        $response = $this->primecontent->compound->getAll();

        $this->assertTrue(count($response)>=1);
    }

    /**
     * @testdox Get single item
     */
    public function testGetSingleItemSuccess(){
        $itemId = "address";
        $response = $this->primecontent->compound->getOne($itemId);

        $this->assertObjectHasAttribute("id",$response);
        $this->assertTrue($response->id === $itemId);
    }

    /**
     * @testdox Get single item not found exception
     */
    public function testGetSingleItemNotFound(){
        $itemId = "test-fail";
        $this->expectException(\Primecontent\Exceptions\ClientException::class);
        $this->expectExceptionCode(404);
        $response = $this->primecontent->compound->getOne($itemId);
    }

    /**
     * @testdox Create item success
     */
    public function testCreateSingleItemSuccess(){
        $type = "custom-field-".random_int(1,1000000);
        $title = "Item create test";
        $description = "Custom field generated by testing";
        $fields = json_decode('{"$schema":"http:\/\/json-schema.org\/draft-06\/schema#","title":"Simple page","type":"object","additionalProperties": false,"properties":{"title":{"type":"string"},"text":{"type":"string"}}}',true);
        $isPublic = false;

        $data = $this->generateItem($type,$title,$description,$fields,$isPublic);

        $response = $this->primecontent->compound->create($data);
        $this->assertObjectHasAttribute("id",$response);
        $this->assertTrue($title === $response->attributes->name);
    }

    /**
     * @testdox Create item missed fields exception
     */
    public function testCreateSingleItemUnsetFieldsException(){
        $type = "custom-field-".random_int(1,1000000);
        $title = "Item create test";
        $description = "Custom field generated by testing";
        $fields = json_decode('{"$schema":"http:\/\/json-schema.org\/draft-06\/schema#","title":"Simple page","type":"object","additionalProperties": false,"properties":{"title":{"type":"string"},"text":{"type":"string"}}}',true);
        $isPublic = false;

        $data = $this->generateItem($type,$title,$description,$fields,$isPublic);
        unset($data["fields"]);

        $this->expectException(\Primecontent\Exceptions\ClientException::class);
        $this->expectExceptionCode(400);
        $response = $this->primecontent->compound->create($data);

    }

    /**
     * @testdox Update item success
     */
    public function testUpdateSingleItemSuccess(){
        $type = "video-test";
        $title = "Item create test";
        $description = "Custom field generated by testing and edited";
        $fields = json_decode('{"$schema":"http:\/\/json-schema.org\/draft-06\/schema#","title":"Simple page","type":"object","additionalProperties": false,"properties":{"title":{"type":"string"},"text":{"type":"string"}}}',true);
        $isPublic = false;

        $data = $this->generateItem($type,$title,$description,$fields,$isPublic);

        $response = $this->primecontent->compound->create($data);
        $itemId = $response->id;
        $randInt = random_int(1,100000);
        $data["name"] = "Item {$randInt} edited!!!!!!";

        $response = $this->primecontent->compound->update($itemId,$data);

        $this->assertTrue($data["name"] === $response->attributes->name);
    }

    /**
     * @testdox Update item not found exception
     */
    public function testUpdateSingleItemNotFoundException(){
        $type = "video-test";
        $title = "Item create test";
        $description = "Custom field generated by testing and edited";
        $fields = json_decode('{"$schema":"http:\/\/json-schema.org\/draft-06\/schema#","title":"Simple page","type":"object","additionalProperties": false,"properties":{"title":{"type":"string"},"text":{"type":"string"}}}',true);
        $isPublic = false;

        $data = $this->generateItem($type,$title,$description,$fields,$isPublic);

        $this->expectException(\Primecontent\Exceptions\ClientException::class);
        $this->expectExceptionCode(404);
        $response = $this->primecontent->compound->update("test-edit-fail",$data);
    }

    /**
     * @testdox Delete item success
     */
    public function testDeleteSingleItemSuccess(){
        $type = "cf-delete";
        $title = "Item delete test";
        $description = "Custom field generated by testing and deleted";
        $fields = json_decode('{"$schema":"http:\/\/json-schema.org\/draft-06\/schema#","title":"Simple page","type":"object","additionalProperties": false,"properties":{"title":{"type":"string"},"text":{"type":"string"}}}',true);
        $isPublic = false;

        $data = $this->generateItem($type,$title,$description,$fields,$isPublic);

        $response = $this->primecontent->compound->create($data);
        $itemId = $response->id;

        $response = $this->primecontent->compound->delete($itemId);

        $this->assertTrue(!$response);
    }

    /**
     * @testdox Delete item not found exception
     */
    public function testDeleteSingleItemNotFoundException(){
        $itemId = "test-fail";
        $this->expectException(\Primecontent\Exceptions\ClientException::class);
        $this->expectExceptionCode(404);
        $response = $this->primecontent->compound->delete($itemId);
    }

    /**
     * @param string $type
     * @param string $name
     * @param string $description
     * @param mixed $fields
     * @param bool $isPublic
     * @return array
     */
    private function generateItem(string $type, string $name,string $description, $fields, bool $isPublic)
    {

        $data = array(
            "type" => $type,
            "name" => $name,
            "description" => $description,
            "fields" => $fields,
            "public" => $isPublic
        );

        return $data;
    }
}
